version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: test
      PASSWORD: test
    volumes:
      - ./dav:/var/lib/dav

